## Bayesian Butterfingers Data Collection

In [7]:
#import statements
import tqdm
import requests
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

### Collecting Data for TN District 7

In [1]:
import retrievedata
retrievedata.retrieve_2020_state_district_data('Tennesee', 7)

No state by the name 'Tennesee'. Assuming you meant 'Tennessee'.

,State_Abbreviation,District,cid,FirstLast,Party,Rcpts,Spent,PACs,Indivs,Cand,...,Result,CRPICO,State,IncCID,Incumbent,primarydate,DistIDCurr,capeye,sort,SmLgIndivsNote
0,TN,07,N00041873,Mark Green,R,1194960.47,935486.67,171900.0,819151.42,0.0,...,W,I,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,TN07,0,1,N
1,TN,07,N00045536,Kiran Sreepada,D,206644.28,207190.98,4000.0,202644.28,0.0,...,L,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,,0,2,N
2,TN,07,N00047077,Ronald Brown,I,1750.00,0.00,0.0,1750.00,0.0,...,L,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,,0,2,N
3,TN,07,N00046592,Scott Vieira Jr,I,655.47,1048.51,10.0,45.00,35.0,...,L,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,,0,2,N
4,TN,07,N00045535,Benjamin Estes,3,0.00,0.00,0.0,0.00,0.0,...,,C,Tennessee,NaN,NaN,2020-08-06 00:00:00 +0000,NaN,0,2,N

In [2]:
retrievedata.state_representatives_df

             State  Total seats Abbreviation
0          Alabama            7           AL
1           Alaska            1           AK
2          Arizona            9           AZ
3         Arkansas            4           AR
4       California           53           CA
5         Colorado            7           CO
6      Connecticut            5           CT
7         Delaware            1           DE
8          Florida           27           FL
9          Georgia           14           GA
10          Hawaii            2           HI
11           Idaho            2           ID
12        Illinois           18           IL
13         Indiana            9           IN
14            Iowa            4           IA
15          Kansas            4           KS
16        Kentucky            6           KY
17       Louisiana            6           LA
18           Maine            2           ME
19        Maryland            8           MD
20   Massachusetts            9           MA
21        Michigan           14           MI
22       Minnesota            8           MN
23     Mississippi            4           MS
24        Missouri            8           MO
25         Montana            1           MT
26        Nebraska            3           NE
27          Nevada            4           NV
28   New Hampshire            2           NH
29      New Jersey           12           NJ
30      New Mexico            3           NM
31        New York           27           NY
32  North Carolina           13           NC
33    North Dakota            1           ND
34            Ohio           16           OH
35        Oklahoma            5           OK
36          Oregon            5           OR
37    Pennsylvania           18           PA
38    Rhode Island            2           RI
39  South Carolina            7           SC
40    South Dakota            1           SD
41       Tennessee            9           TN
42           Texas           36           TX
43            Utah            4           UT
44         Vermont            1           VT
45        Virginia           11           VA
46      Washington           10           WA
47   West Virginia            3           WV
48       Wisconsin            8           WI
49         Wyoming            1           WY

In [5]:
retrievedata.retrieve_2020_state_district_data('SG', 1)

No state abbreviation by the name 'SG'. Assuming you meant 'GA'.

,State_Abbreviation,District,cid,FirstLast,Party,Rcpts,Spent,PACs,Indivs,Cand,...,Result,CRPICO,State,IncCID,Incumbent,primarydate,DistIDCurr,capeye,sort,SmLgIndivsNote
0,GA,01,N00035346,Buddy Carter,R,2315487.13,1734753.96,1205934.0,1135759.61,0.0,...,W,I,Georgia,NaN,NaN,2020-05-19 00:00:00 +0000,GA01,0,1,N
1,GA,01,N00013262,Joyce Griggs,D,130043.17,125000.33,2250.0,56064.17,70729.0,...,L,C,Georgia,NaN,NaN,2020-05-19 00:00:00 +0000,,0,2,N

## Getting All Data and Saving as .csv

In [7]:
#retrievedata.get_all_data().reset_index(drop=True).to_csv('All_2020_Election_Data.csv', index=None)

In [14]:
election_df = pd.read_csv('All_2020_Election_Data.csv')
election_df

,State_Abbreviation,District,cid,FirstLast,Party,Rcpts,Spent,PACs,Indivs,Cand,...,Result,CRPICO,State,IncCID,Incumbent,primarydate,DistIDCurr,capeye,sort,SmLgIndivsNote
0,AL,1,N00044245,Jerry Carl,R,1971321.50,1859348.91,387000.00,1044195.95,434655.50,...,W,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
1,AL,1,N00044750,James Averhart,D,80094.95,78973.24,0.00,50849.95,29245.00,...,L,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
2,AL,2,N00041295,Barry Moore,R,650806.75,669367.70,230281.65,408536.20,11500.00,...,W,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
3,AL,2,N00045944,Phyllis Harvey-Hall,D,56049.68,55988.07,2032.00,42411.95,10575.41,...,L,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,,0,2,N
4,AL,2,N00045631,John Page,L,0.00,0.00,0.00,0.00,0.00,...,,O,Alabama,NaN,NaN,2020-03-03 00:00:00 +0000,NaN,0,2,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1259,WY,1,N00035504,Liz Cheney,R,3003883.34,3060166.78,1292490.00,1169995.46,0.00,...,W,I,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,WY01,0,1,N
1260,WY,1,N00047272,Lynnette Grey Bull,D,134597.32,132234.75,2800.00,130197.32,0.00,...,L,C,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,,0,2,N
1261,WY,1,N00047207,Zoilo Adalia,3,0.00,0.00,0.00,0.00,0.00,...,,C,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,NaN,0,2,N
1262,WY,1,N00035139,Richard Brubaker,L,0.00,0.00,0.00,0.00,0.00,...,,C,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,NaN,0,2,N
1263,WY,1,N00047495,Jeff Haggit,3,0.00,0.00,0.00,0.00,0.00,...,,C,Wyoming,NaN,NaN,2020-08-18 00:00:00 +0000,NaN,0,2,N